# Tasks (PyTorch)

1. Load Datset (Training/Testing)
2. Format Dataset
3. Class for Dataset/Dataloader
4. Class for Neural Network (NN)
5. Training
    i. defining Training loop/ numOfEpochs
    ii. Dataload to NN
    iii. Forward Propagation
    iv. Loss computation
    v. Backpropagation/gradient computation
    vi. update weights

In [ ]:
#IMPORT libraries

In [191]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
import numpy as np
#import os
#import time

In [192]:
#path = "/content/sample_data/activity_monitoring/"
#path = "/content/sample_data/"
path = 'D:\\University\\Machine learning\\project\\'

In [193]:
#load dataset
train_msAcc = np.load(path+"training\\"+"trainMSAccelerometer.npy")
train_msGyro = np.load(path+"training\\"+"trainMSGyroscope.npy")
train_Acc = np.load(path+"training\\"+"trainAccelerometer.npy")
train_Grav = np.load(path+"training\\"+"trainGravity.npy")
train_jinAcc = np.load(path+"training\\"+"trainJinsAccelerometer.npy")
train_jinGyro = np.load(path+"training\\"+"trainJinsGyroscope.npy")
train_liAcc = np.load(path+"training\\"+"trainLinearAcceleration.npy")
train_Mag = np.load(path+"training\\"+"trainMagnetometer.npy")
train_Gyro = np.load(path+"training\\"+"trainGyroscope.npy")
train_labels = np.load(path+"training\\"+"trainlabels.npy")

test_msAcc = np.load(path+"testing\\"+"testMSAccelerometer.npy")
test_msGyro = np.load(path+"testing\\"+"testMSGyroscope.npy")
test_Acc = np.load(path+"testing\\"+"testAccelerometer.npy")
test_Grav = np.load(path+"testing\\"+"testGravity.npy")
test_jinAcc = np.load(path+"testing\\"+"testJinsAccelerometer.npy")
test_jinGyro = np.load(path+"testing\\"+"testJinsGyroscope.npy")
test_liAcc = np.load(path+"testing\\"+"testLinearAcceleration.npy")
test_Mag = np.load(path+"testing\\"+"testMagnetometer.npy")
test_Gyro = np.load(path+"testing\\"+"testGyroscope.npy")
test_labels = np.load(path+"testing\\"+"testlabels.npy")




In [194]:
print(train_msAcc.shape)
print(train_msGyro.shape)
print(train_Acc.shape)
print(train_Grav.shape)
print(train_jinAcc.shape)
print(train_jinGyro.shape)
print(train_liAcc.shape)
print(train_Mag.shape)
print(train_Gyro.shape)
print(train_labels.shape)

print(test_msAcc.shape)
print(test_msGyro.shape)
print(test_jinAcc.shape)
print(test_Grav.shape)
print(test_jinGyro.shape)
print(test_liAcc.shape)
print(test_Mag.shape)
print(test_Gyro.shape)
print(test_Acc.shape)
print(test_labels.shape)

(2284, 268, 3)
(2284, 268, 3)
(2284, 800, 3)
(2284, 800, 3)
(2284, 80, 3)
(2284, 80, 3)
(2284, 800, 3)
(2284, 200, 3)
(2284, 800, 3)
(2284,)
(2288, 268, 3)
(2288, 268, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 200, 3)
(2288, 800, 3)
(2288, 800, 3)
(2288,)


In [195]:
#for CNN
# train_msAcc Gyrorain_msAcc.transpose((0,2,1))
# test_estc = test_msAcc.transpose((0,2,1))
print(test_msGyro.shape)
# train_msGyro = train_msGyro.transpose((0,2,1))
# test_msGyro = test_msGyro.transpose((0,2,1))

print(train_msAcc.shape) #87,3,268
print(train_msGyro.shape)
print(test_msAcc.shape)
print(test_msGyro.shape)

#for linear NN
train_msAcc = np.reshape(train_msAcc, (train_msAcc.shape[0],train_msAcc.shape[1]*train_msAcc.shape[2]))
train_msGyro = np.reshape(train_msGyro, (train_msGyro.shape[0],train_msGyro.shape[1]*train_msGyro.shape[2]))
train_Acc = np.reshape(train_Acc, (train_Acc.shape[0],train_Acc.shape[1]*train_Acc.shape[2]))
train_Grav = np.reshape(train_Grav, (train_Grav.shape[0],train_Grav.shape[1]*train_Grav.shape[2]))
train_jinAcc = np.reshape(train_jinAcc, (train_jinAcc.shape[0],train_jinAcc.shape[1]*train_jinAcc.shape[2]))
train_jinGyro = np.reshape(train_jinGyro, (train_jinGyro.shape[0],train_jinGyro.shape[1]*train_jinGyro.shape[2]))
train_liAcc = np.reshape(train_liAcc, (train_liAcc.shape[0],train_liAcc.shape[1]*train_liAcc.shape[2]))
train_Mag = np.reshape(train_Mag, (train_Mag.shape[0],train_Mag.shape[1]*train_Mag.shape[2]))
train_Gyro = np.reshape(train_Gyro, (train_Gyro.shape[0],train_Gyro.shape[1]*train_Gyro.shape[2]))

test_msAcc = np.reshape(test_msAcc, (test_msAcc.shape[0],test_msAcc.shape[1]*test_msAcc.shape[2]))
test_msGyro = np.reshape(test_msGyro, (test_msGyro.shape[0],test_msGyro.shape[1]*test_msGyro.shape[2]))
test_Acc = np.reshape(test_Acc, (test_Acc.shape[0],test_Acc.shape[1]*test_Acc.shape[2]))
test_Grav = np.reshape(test_Grav, (test_Grav.shape[0],test_Grav.shape[1]*test_Grav.shape[2]))
test_jinAcc = np.reshape(test_jinAcc, (test_jinAcc.shape[0],test_jinAcc.shape[1]*test_jinAcc.shape[2]))
test_jinGyro = np.reshape(test_jinGyro, (test_jinGyro.shape[0],test_jinGyro.shape[1]*test_jinGyro.shape[2]))
test_liAcc = np.reshape(test_liAcc, (test_liAcc.shape[0],test_liAcc.shape[1]*test_liAcc.shape[2]))
test_Mag = np.reshape(test_Mag, (test_Mag.shape[0],test_Mag.shape[1]*test_Mag.shape[2]))
test_Gyro = np.reshape(test_Gyro, (test_Gyro.shape[0],test_Gyro.shape[1]*test_Gyro.shape[2]))

print(f"msAcc: {train_msAcc.shape}")
print(f"msGyro {train_msGyro.shape}")
print(train_Acc.shape)
print(train_Grav.shape)
print(train_jinAcc.shape)
print(train_jinGyro.shape)
print(train_liAcc.shape)
print(train_Mag.shape)
print(train_Gyro.shape)
print(train_labels.shape)


(2288, 268, 3)
(2284, 268, 3)
(2284, 268, 3)
(2288, 268, 3)
(2288, 268, 3)
msAcc: (2284, 804)
msGyro (2284, 804)
(2284, 2400)
(2284, 2400)
(2284, 240)
(2284, 240)
(2284, 2400)
(2284, 600)
(2284, 2400)
(2284,)


[47 47 22 ... 33 29 28]
[0 0 0 ... 0 0 0]
[17 10 34 ... 29 34 10]
[0 0 0 ... 0 0 0]


In [197]:
#cogAge class to hold data
class CogAgeDataset(Dataset):
    def __init__(self, cd_msAcc, cd_msGyro, cd_Acc, cd_Grav, cd_jinAcc, cd_jinGyro, cd_liAcc, cd_Mag, cd_Gyro, cd_labels ):
        self.msAcc = cd_msAcc
        self.msGyro = cd_msGyro
        self.cd_Gyro = cd_Gyro
        self.cd_Acc = cd_Acc
        self.cd_Grav = cd_Grav
        self.cd_jinAcc = cd_jinAcc
        self.cd_jinGyro = cd_jinGyro
        self.cd_liAcc = cd_liAcc
        self.cd_Mag = cd_Mag
        self.labels = cd_labels
        
    def __len__(self):
        return len(self.msAcc)

    def __getitem__(self, index):
        return (self.msAcc[index], self.msGyro[index], self.cd_Acc[index], self.cd_Grav[index], self.cd_jinAcc[index], self.cd_jinGyro[index], self.cd_liAcc[index], self.cd_Mag[index], self.cd_Gyro[index], self.labels[index])

In [198]:
# activity monitoring
class ActivityMonitoring_FC(nn.Module):

    def __init__(self):
        super(ActivityMonitoring_FC, self).__init__()
        
        self.fc11 = nn.Linear(804 , 1024)  #msacc # flatten inpu dimension
        self.fc12 = nn.Linear(804 , 1024) #msgyro
        self.fc13 = nn.Linear(2400 , 1024)  #acc # flatten inpu dimension
        self.fc14 = nn.Linear(2400 , 1024) #grav
        self.fc15 = nn.Linear(240 , 1024)  #jinAcc # flatten inpu dimension
        self.fc16 = nn.Linear(240 , 1024) #jinGyro
        self.fc17 = nn.Linear(2400 , 1024)  #liAcc # flatten inpu dimension
        self.fc18 = nn.Linear(600 , 1024) #mag
        self.fc19 = nn.Linear(2400 , 1024)  #gyro # flatten inpu dimension 
        
        self.fc21 = nn.Linear(1024 , 512)
        self.fc22 = nn.Linear(1024 , 512)
        self.fc23 = nn.Linear(1024 , 512)  #acc # flatten inpu dimension
        self.fc24 = nn.Linear(1024 , 512) #grav
        self.fc25 = nn.Linear(1024 , 512)  #jinAcc # flatten inpu dimension
        self.fc26 = nn.Linear(1024 , 512) #jinGyro
        self.fc27 = nn.Linear(1024 , 512)  #liAcc # flatten inpu dimension
        self.fc28 = nn.Linear(1024 , 512) #mag
        self.fc29 = nn.Linear(1024 , 512)  #gyro # flatten inpu dimension 
        
        self.fc3 = nn.Linear(4608 , 2304)
        self.fc4 = nn.Linear(2304 , 1152)
        # self.fc5 = nn.Linear(1152 , 576)
        # self.fc6 = nn.Linear(576 , 288)

        # self.output = nn.Linear(288 , 55)
        self.output = nn.Linear(1152 , 55)
        self.dropout1 = nn.Dropout(p=0.3)
        self.dropout2 = nn.Dropout(p=0.3)

    def forward(self, msAcc, msGyro, Acc, Grav, jinAcc, jinGyro, liAcc, Mag, Gyro):

        # print("msAcc input shape:", msAcc.shape)
        msAcc = self.fc11(msAcc) #z-vector
        msAcc = F.relu(msAcc)
        msAcc = self.fc21(msAcc)
        msAcc = F.relu(msAcc)

        # print("msAcc.shape:", msAcc.shape)


        # print("msGyro input shape:", msGyro.shape)
        msGyro = self.fc12(msGyro)
        msGyro = F.relu(msGyro)
        msGyro = self.fc22(msGyro)
        msGyro = F.relu(msGyro)

        # print("msGyro.shape:", msGyro.shape)

        # print("Acc input shape:", Acc.shape)
        Acc = self.fc13(Acc)
        Acc = F.relu(Acc)
        Acc = self.fc23(Acc)
        Acc = F.relu(Acc)

        # print("Acc.shape:", Acc.shape)
        # print("input shape:", Grav.shape)
        Grav = self.fc14(Grav)
        Grav = F.relu(Grav)
        Grav = self.fc24(Grav)
        Grav = F.relu(Grav)

        # print("msGyro.shape:", Grav.shape)
        # print("input shape:", jinAcc.shape)
        jinAcc = self.fc15(jinAcc)
        jinAcc = F.relu(jinAcc)
        jinAcc = self.fc25(jinAcc)
        jinAcc = F.relu(jinAcc)

        # print("msGyro.shape:", jinAcc.shape)
        # print("input shape:", msGyro.shape)
        jinGyro = self.fc16(jinGyro)
        jinGyro = F.relu(jinGyro)
        jinGyro = self.fc26(jinGyro)
        jinGyro = F.relu(jinGyro)

        # print("msGyro.shape:", msGyro.shape)
        # print("input shape:", msGyro.shape)
        liAcc = self.fc17(liAcc)
        liAcc = F.relu(liAcc)
        liAcc = self.fc27(liAcc)
        liAcc = F.relu(liAcc)

        # print("msGyro.shape:", msGyro.shape)
        # print("input shape:", msGyro.shape)
        Mag = self.fc18(Mag)
        Mag = F.relu(Mag)
        Mag = self.fc28(Mag)
        Mag = F.relu(Mag)

        # print("msGyro.shape:", msGyro.shape)
        
        # print("input shape:", msGyro.shape)
        Gyro = self.fc19(Gyro)
        Gyro = F.relu(Gyro)
        Gyro = self.fc29(Gyro)
        Gyro = F.relu(Gyro)

        # print("msGyro.shape:", msGyro.shape)
        
        joint_channels = torch.cat(( msAcc, msGyro, Acc, Grav, jinAcc, jinGyro, liAcc, Mag, Gyro), 1)
        # print("joint_channels.shape after concat:", joint_channels.shape)
        act = F.relu(self.fc3(joint_channels))
        # print("act shape after fc3: ", act.shape)
        act = F.relu(self.fc4(act))
        # act = F.relu(self.fc5(act))
        act = self.dropout1(act)
        # act = F.relu(self.fc6(act))
        # print("act shape after fc4: ", act.shape)
        act = self.dropout2(act)
        act_out = self.output(act)
        # print("act_out shape after output layer: ", act_out.shape)

        return act_out



In [199]:
#defining loss_fn, optimizer, model
lr = 0.01
act_model = ActivityMonitoring_FC()
optimizer_act = optim.Adam(act_model.parameters(), lr=lr) #for state activities

loss_fn = nn.CrossEntropyLoss()
batch_size = 10

In [200]:
#load dataset
train_dataset = CogAgeDataset(train_msAcc, train_msGyro,train_Acc,train_Grav,train_jinAcc,train_jinGyro,train_liAcc,train_Mag,train_Gyro, train_labels)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = CogAgeDataset(test_msAcc, test_msGyro,test_Acc,test_Grav,test_jinAcc,test_jinGyro,test_liAcc,test_Mag,test_Gyro, test_labels)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    

In [201]:
#training = 0
samples_tr = 0
correct_tr = 0
act_model.train()
n_epochs = 5
for epoch in range(n_epochs): #training loop
    batch_losses = []

    act_sample_tr = 0
    act_sample_ts = 0
    for msAcc_tr, msGyro_tr, Acc_tr, Grav_tr, jinAcc_tr, jinGyro_tr, liAcc_tr, Mag_tr, Gyro_tr, labels_tr in train_loader:
            # print("Dimensions of each sensor modality:")
            # print(f"msAcc_tr: {msAcc_tr.shape}")
            # print(f"msGyro_tr: {msGyro_tr.shape}")
            # print(f"bbh_labels_tr: {labels_tr.shape}")

            
            #labels_tr  = labels_tr.to(device)
            
            
            optimizer_act.zero_grad()

            labels_predicted = act_model(msAcc_tr, msGyro_tr, Acc_tr, Grav_tr, jinAcc_tr, jinGyro_tr, liAcc_tr, Mag_tr, Gyro_tr)
            #labels_predicted = labels_predicted.flatten()
            labels_tr = labels_tr.type(torch.LongTensor)

            _, predicted_tr = torch.max(labels_predicted,1)
            #print("predicted_tr.shape", predicted_tr.shape)   

            samples_tr += labels_tr.size(0)
            correct_tr += (predicted_tr == labels_tr).sum().item()
            loss = loss_fn(labels_predicted, labels_tr)
            loss = loss.unsqueeze(0)
            epoch_loss = loss.item()
            print("Epoch, Loss:" , epoch,", ", epoch_loss)
            batch_losses.append(loss.item())
            
            loss.backward()
            optimizer_act.step()

    act_loss = sum(batch_losses)/len(batch_losses)
        #average_loss[1].append(bbh_loss)
    accr = 100.0 * correct_tr / samples_tr

    print(f"epoch: {epoch}")
    print(f"Training: batch_loss: {act_loss:.3f}, Accuracy: {accr:.3f}")
    #print(f"Training: batch_loss: {act_loss:.3f}, {state_correct_tr}/{state_samples_tr}, state_acc: {state_acc:.3f}%,  bbh_loss: {bbh_loss:.3f}, {bbh_correct_tr}/{bbh_samples_tr} , bbh_acc: {bbh_acc:.3f}%")

 

Epoch, Loss: 0 ,  3.9030890464782715
Epoch, Loss: 0 ,  25614.69921875
Epoch, Loss: 0 ,  192.33340454101562
Epoch, Loss: 0 ,  136.64605712890625
Epoch, Loss: 0 ,  162.241455078125
Epoch, Loss: 0 ,  82.41606140136719
Epoch, Loss: 0 ,  492.99713134765625
Epoch, Loss: 0 ,  201.8343505859375
Epoch, Loss: 0 ,  166.58395385742188
Epoch, Loss: 0 ,  105.84175109863281
Epoch, Loss: 0 ,  668.7124633789062
Epoch, Loss: 0 ,  111.78501892089844
Epoch, Loss: 0 ,  103.82469177246094
Epoch, Loss: 0 ,  148.82534790039062
Epoch, Loss: 0 ,  135.23855590820312
Epoch, Loss: 0 ,  111.2412109375
Epoch, Loss: 0 ,  93.84623718261719
Epoch, Loss: 0 ,  73.2242431640625
Epoch, Loss: 0 ,  79.16683959960938
Epoch, Loss: 0 ,  71.73094940185547
Epoch, Loss: 0 ,  106.4382553100586
Epoch, Loss: 0 ,  108.60919189453125
Epoch, Loss: 0 ,  44.06578063964844
Epoch, Loss: 0 ,  42.920772552490234
Epoch, Loss: 0 ,  19.23505210876465
Epoch, Loss: 0 ,  21.78750991821289
Epoch, Loss: 0 ,  19.755746841430664
Epoch, Loss: 0 ,  10.81

In [202]:
#F1 Score
from sklearn.metrics import f1_score
f1 = f1_score(labels_tr, predicted_tr,average="macro")
print("F1 score: ", f1)

F1 score:  0.1


In [210]:
print(predicted_tr.float().mean())

tensor(20.)


In [213]:
from sklearn.metrics import precision_score

print(precision_score(labels_tr, predicted_tr,average="macro"))

0.0625


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
