In [49]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
import torch
import torch.nn as nn

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, TensorDataset
import numpy as np

In [50]:
path = 'D:\\University\\Machine learning\\project\\'
train_Acc= np.load(path + "training\\" + "trainAccelerometer.npy")
train_Grav= np.load(path + "training\\" + "trainGravity.npy")
train_Gyro= np.load(path + "training\\" + "trainGyroscope.npy")
train_JinAcc= np.load(path + "training\\" + "trainJinsAccelerometer.npy")
train_JinGyro= np.load(path + "training\\" + "trainJinsGyroscope.npy")
train_LintAcc= np.load(path + "training\\" + "trainLinearAcceleration.npy")
train_Magn= np.load(path + "training\\" + "trainMagnetometer.npy")
train_MSAcc= np.load(path + "training\\" + "trainMSAccelerometer.npy")
train_MSGyro= np.load(path + "training\\" + "trainMSGyroscope.npy")

AS there are same no of examples in each file so checking shape for any one

In [51]:
print(train_Acc.shape)
print(train_Grav.shape)
print(train_Gyro.shape)
print(train_JinAcc.shape)
print(train_JinGyro.shape)
print(train_LintAcc.shape)
print(train_Magn.shape)
print(train_MSAcc.shape)
print(train_MSGyro.shape)

(2284, 800, 3)
(2284, 800, 3)
(2284, 800, 3)
(2284, 80, 3)
(2284, 80, 3)
(2284, 800, 3)
(2284, 200, 3)
(2284, 268, 3)
(2284, 268, 3)


In [52]:
train_Labels= np.load(path + "training\\" + "trainLabels.npy")

In [53]:
print(train_Labels.shape)

(2284,)


In [54]:
test_Acc= np.load(path + "testing\\" + "testAccelerometer.npy")
test_Grav= np.load(path + "testing\\" + "testGravity.npy")
test_Gyro= np.load(path + "testing\\" + "testGyroscope.npy")
test_JinAcc= np.load(path + "testing\\" + "testJinsAccelerometer.npy")
test_JinGyro= np.load(path + "testing\\" + "testJinsGyroscope.npy")
test_LintAcc= np.load(path + "testing\\" + "testLinearAcceleration.npy")
test_Magn= np.load(path + "testing\\" + "testMagnetometer.npy")
test_MSAcc= np.load(path + "testing\\" + "testMSAccelerometer.npy")
test_MSGyro= np.load(path + "testing\\" + "testMSGyroscope.npy")

In [55]:
print(test_Acc.shape)
print(test_Grav.shape)
print(test_Gyro.shape)
print(test_JinAcc.shape)
print(test_JinGyro.shape)
print(test_LintAcc.shape)
print(test_Magn.shape)
print(test_MSAcc.shape)
print(test_MSGyro.shape)

(2288, 800, 3)
(2288, 800, 3)
(2288, 800, 3)
(2288, 80, 3)
(2288, 80, 3)
(2288, 800, 3)
(2288, 200, 3)
(2288, 268, 3)
(2288, 268, 3)


In [56]:
test_Labels= np.load(path + "testing\\" + "testLabels.npy")

In [57]:
print(test_Labels.shape)

(2288,)


In [58]:
train_numof_examples = np.shape(train_Labels)[0]
test_numof_examples = np.shape(test_Labels)[0]
print("Number of Train Examples: ", train_numof_examples)
print("Number of Test Examples: ", train_numof_examples)

Number of Train Examples:  2284
Number of Test Examples:  2284


In [59]:
numof_features = 4
train_features = np.zeros((train_numof_examples, 9*numof_features, 3))
test_features = np.zeros((test_numof_examples, 9*numof_features, 3))

print(np.shape(train_features))
print(np.shape(test_features))

(2284, 36, 3)
(2288, 36, 3)


In [60]:
train_features[:,0,:] = np.mean(train_Acc, axis=1)
train_features[:,1,:] = np.max(train_Acc, axis=1)
train_features[:,2,:] = np.min(train_Acc, axis=1)
train_features[:,3,:] = np.std(train_Acc, axis=1)

train_features[:,4,:] = np.mean(train_Gyro, axis=1)
train_features[:,5,:] = np.max(train_Gyro, axis=1)
train_features[:,6,:] = np.min(train_Gyro, axis=1)
train_features[:,7,:] = np.std(train_Gyro, axis=1)

train_features[:,8,:] = np.mean(train_Grav, axis=1)
train_features[:,9,:] = np.max(train_Grav, axis=1)
train_features[:,10,:] = np.min(train_Grav, axis=1)
train_features[:,11,:] = np.std(train_Grav, axis=1)

train_features[:,12,:] = np.mean(train_JinAcc, axis=1)
train_features[:,13,:] = np.max(train_JinAcc, axis=1)
train_features[:,14,:] = np.min(train_JinAcc, axis=1)
train_features[:,15,:] = np.std(train_JinAcc, axis=1)

train_features[:,16,:] = np.mean(train_JinGyro, axis=1)
train_features[:,17,:] = np.max(train_JinGyro, axis=1)
train_features[:,18,:] = np.min(train_JinGyro, axis=1)
train_features[:,19,:] = np.std(train_JinGyro, axis=1)

train_features[:,20,:] = np.mean(train_LintAcc, axis=1)
train_features[:,21,:] = np.max(train_LintAcc, axis=1)
train_features[:,22,:] = np.min(train_LintAcc, axis=1)
train_features[:,23,:] = np.std(train_LintAcc, axis=1)

train_features[:,24,:] = np.mean(train_MSGyro, axis=1)
train_features[:,25,:] = np.max(train_MSGyro, axis=1)
train_features[:,26,:] = np.min(train_MSGyro, axis=1)
train_features[:,27,:] = np.std(train_MSGyro, axis=1)

train_features[:,28,:] = np.mean(train_Magn, axis=1)
train_features[:,29,:] = np.max(train_Magn, axis=1)
train_features[:,30,:] = np.min(train_Magn, axis=1)
train_features[:,31,:] = np.std(train_Magn, axis=1)

train_features[:,32,:] = np.mean(train_MSAcc, axis=1)
train_features[:,33,:] = np.max(train_MSAcc, axis=1)
train_features[:,34,:] = np.min(train_MSAcc, axis=1)
train_features[:,35,:] = np.std(train_MSAcc, axis=1)

In [61]:
print(train_features[:,0,:])
print(train_features[:,1,:])
print(train_features[:,2,:])
print(train_features[:,3,:])
print(train_features[:,4,:])
print(train_features[:,5,:])
print(train_features[:,6,:])
print(train_features[:,7,:])
print(train_features[:,8,:])
print(train_features[:,9,:])
print(train_features[:,10,:])
print(train_features[:,11,:])
print(train_features[:,12,:])
print(train_features[:,13,:])
print(train_features[:,14,:])
print(train_features[:,15,:])
print(train_features[:,16,:])
print(train_features[:,17,:])
print(train_features[:,18,:])
print(train_features[:,19,:])
print(train_features[:,20,:])
print(train_features[:,21,:])
print(train_features[:,22,:])
print(train_features[:,23,:])
print(train_features[:,24,:])
print(train_features[:,25,:])
print(train_features[:,26,:])
print(train_features[:,27,:])
print(train_features[:,28,:])
print(train_features[:,29,:])
print(train_features[:,30,:])
print(train_features[:,31,:])
print(train_features[:,32,:])
print(train_features[:,33,:])
print(train_features[:,34,:])
print(train_features[:,35,:])

[[-0.33403057 10.52975368 -1.05092883]
 [ 0.27308881 10.55872822 -1.04610538]
 [-0.12369978  2.32891917 -9.68883991]
 ...
 [-0.6406647  10.29317379 -2.28113747]
 [-7.14991951  7.45246696  0.12904663]
 [-0.34671208  1.92669535 -9.74248505]]
[[ 4.36851597e+00  1.74357433e+01  5.06067657e+00]
 [ 2.20820808e+00  1.51556845e+01  2.19383788e+00]
 [ 3.68833035e-01  2.74469256e+00 -9.36213207e+00]
 ...
 [ 1.65016854e+00  1.52945957e+01  4.45473641e-01]
 [-6.84496593e+00  7.75986338e+00  3.99968266e-01]
 [ 1.43701173e-02  2.10761738e+00 -9.47948742e+00]]
[[-5.15647745  6.39709759 -7.41737604]
 [-3.41290307  8.46399975 -4.96008587]
 [-0.88615727  2.00942159 -9.93693638]
 ...
 [-2.36867452  7.71675348 -5.7217021 ]
 [-7.44132614  7.20421886 -0.25866213]
 [-0.67539555  1.70764899 -9.94412136]]
[[1.5876956  1.38067472 1.75546467]
 [1.13384628 0.79438061 1.29178071]
 [0.28708279 0.08189599 0.07745841]
 ...
 [0.90534979 0.8697201  1.34667611]
 [0.08446047 0.08195577 0.10580464]
 [0.10053312 0.06906944

In [62]:
test_features[:,0,:] = np.mean(test_Acc, axis=1)
test_features[:,1,:] = np.max(test_Acc, axis=1)
test_features[:,2,:] = np.min(test_Acc, axis=1)
test_features[:,3,:] = np.std(test_Acc, axis=1)

test_features[:,4,:] = np.mean(test_Gyro, axis=1)
test_features[:,5,:] = np.max(test_Gyro, axis=1)
test_features[:,6,:] = np.min(test_Gyro, axis=1)
test_features[:,7,:] = np.std(test_Gyro, axis=1)

test_features[:,8,:] = np.mean(test_Grav, axis=1)
test_features[:,9,:] = np.max(test_Grav, axis=1)
test_features[:,10,:] = np.min(test_Grav, axis=1)
test_features[:,11,:] = np.std(test_Grav, axis=1)

test_features[:,12,:] = np.mean(test_JinAcc, axis=1)
test_features[:,13,:] = np.max(test_JinAcc, axis=1)
test_features[:,14,:] = np.min(test_JinAcc, axis=1)
test_features[:,15,:] = np.std(test_JinAcc, axis=1)

test_features[:,16,:] = np.mean(test_JinGyro, axis=1)
test_features[:,17,:] = np.max(test_JinGyro, axis=1)
test_features[:,18,:] = np.min(test_JinGyro, axis=1)
test_features[:,19,:] = np.std(test_JinGyro, axis=1)

test_features[:,20,:] = np.mean(test_LintAcc, axis=1)
test_features[:,21,:] = np.max(test_LintAcc, axis=1)
test_features[:,22,:] = np.min(test_LintAcc, axis=1)
test_features[:,23,:] = np.std(test_LintAcc, axis=1)

test_features[:,24,:] = np.mean(test_MSGyro, axis=1)
test_features[:,25,:] = np.max(test_MSGyro, axis=1)
test_features[:,26,:] = np.min(test_MSGyro, axis=1)
test_features[:,27,:] = np.std(test_MSGyro, axis=1)

test_features[:,28,:] = np.mean(test_Magn, axis=1)
test_features[:,29,:] = np.max(test_Magn, axis=1)
test_features[:,30,:] = np.min(test_Magn, axis=1)
test_features[:,31,:] = np.std(test_Magn, axis=1)

test_features[:,32,:] = np.mean(test_MSAcc, axis=1)
test_features[:,33,:] = np.max(test_MSAcc, axis=1)
test_features[:,34,:] = np.min(test_MSAcc, axis=1)
test_features[:,35,:] = np.std(test_MSAcc, axis=1)

In [63]:
print(test_features[:,0,:])
print(test_features[:,1,:])
print(test_features[:,2,:])
print(test_features[:,3,:])
print(test_features[:,4,:])
print(test_features[:,5,:])
print(test_features[:,6,:])
print(test_features[:,7,:])
print(test_features[:,8,:])
print(test_features[:,9,:])
print(test_features[:,10,:])
print(test_features[:,11,:])
print(test_features[:,12,:])
print(test_features[:,13,:])
print(test_features[:,14,:])
print(test_features[:,15,:])
print(test_features[:,16,:])
print(test_features[:,17,:])
print(test_features[:,18,:])
print(test_features[:,19,:])
print(test_features[:,20,:])
print(test_features[:,21,:])
print(test_features[:,22,:])
print(test_features[:,23,:])
print(test_features[:,24,:])
print(test_features[:,25,:])
print(test_features[:,26,:])
print(test_features[:,27,:])
print(test_features[:,28,:])
print(test_features[:,29,:])
print(test_features[:,30,:])
print(test_features[:,31,:])
print(test_features[:,32,:])
print(test_features[:,33,:])
print(test_features[:,34,:])
print(test_features[:,35,:])

[[ 6.14128923  2.07073951 -3.35416722]
 [ 0.87348747  1.85613465 -9.74030876]
 [ 1.5303421   2.40748596 -9.61941242]
 ...
 [-0.68709493 10.6480093   0.56287748]
 [ 2.77206182  1.20917988 -9.44092751]
 [ 2.33061004 10.48865032 -0.30793375]]
[[15.14849949 12.23375988  3.28117681]
 [ 1.09691894  2.05971694 -9.54654789]
 [ 1.95673108  2.74469256 -9.42200756]
 ...
 [-0.24908204 10.8518343   1.15679443]
 [ 3.41529799  1.81302989 -8.61728096]
 [ 2.64649677 10.60514736 -0.10538086]]
[[ -2.50998068  -9.5513382  -12.1307745 ]
 [  0.6610254    1.65016854  -9.9297514 ]
 [  0.99393314   2.02858162  -9.82437038]
 ...
 [ -1.21906495  10.48300076   0.14849122]
 [  1.99505138  -2.3758595  -10.38241005]
 [  2.09803724  10.33450985  -0.58917481]]
[[3.94134235 5.67415142 2.47781754]
 [0.06900784 0.04711317 0.05924704]
 [0.18145226 0.11984875 0.06808255]
 ...
 [0.14435916 0.05665727 0.16252215]
 [0.19693923 0.76158905 0.16718502]
 [0.08395448 0.04479599 0.07245281]]
[[ 4.34666514e-01 -1.69214785e-01  2.263

In [64]:
print(np.shape(train_features))
train_features_reshaped = np.reshape(train_features, (np.shape(train_features)[0], np.shape(train_features)[1]*np.shape(train_features)[2] ))
print(np.shape(train_features_reshaped))


print(np.shape(test_features))
test_features_reshaped = np.reshape(test_features, (np.shape(test_features)[0], np.shape(test_features)[1]*np.shape(test_features)[2] ))
print(np.shape(test_features_reshaped))


(2284, 36, 3)
(2284, 108)
(2288, 36, 3)
(2288, 108)


In [65]:
classfier = SVC(C=1.0, kernel='linear')  
classfier.fit(train_features_reshaped,train_Labels)
estimatedLabels = classfier.predict(test_features_reshaped)

accuracy = accuracy_score(test_Labels,estimatedLabels)
weightedF1 = f1_score(test_Labels,estimatedLabels,average='weighted')
averageF1 = f1_score(test_Labels,estimatedLabels,average='macro')
allF1Scores = f1_score(test_Labels,estimatedLabels,average=None)
conf_matrix = confusion_matrix(test_Labels,estimatedLabels)


In [66]:
print('   C = 1.0 ')
print('   Average F1-score = %.4f' % (averageF1))
print('   Test accuracy = %.2f %%' % (accuracy*100))
print('   Weighted F1-score = %.4f' % (weightedF1))
print('   All F1-scores:')
print(allF1Scores)
print('   Confusion Matrix:')
print(conf_matrix)

print('-------------------------------------------------------')

   C = 1.0 
   Average F1-score = 0.4507
   Test accuracy = 45.37 %
   Weighted F1-score = 0.4495
   All F1-scores:
[0.88372093 0.7047619  0.31707317 0.44897959 0.38383838 0.32183908
 0.48854962 0.20224719 0.02173913 0.36734694 0.41025641 0.53333333
 0.72527473 0.36697248 0.44155844 0.82222222 0.52727273 0.72289157
 0.32911392 0.34285714 0.36170213 0.33707865 0.3908046  0.07017544
 0.09638554 0.58536585 0.4109589  0.2278481  0.56410256 0.36585366
 0.41304348 0.29411765 0.58666667 0.49411765 0.26168224 0.32323232
 0.52307692 0.28571429 0.58823529 0.66666667 0.67391304 0.56716418
 0.34782609 0.49350649 0.8        0.34482759 0.21978022 0.25714286
 0.59259259 0.58666667 0.54285714 0.56410256 0.32       0.62857143
 0.63888889]
   Confusion Matrix:
[[38  0  0 ...  0  0  0]
 [ 0 37  4 ...  1  0  0]
 [ 1  6 13 ...  3  0  0]
 ...
 [ 0  0  3 ... 16  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 1  0  0 ...  3  0 23]]
-------------------------------------------------------


In [96]:
class CogAgeDataset(Dataset):
    def __init__(self, features_reshaped, cd_Labels):
        print(f"tttt: {features_reshaped.shape}")
        self.features_reshaped = features_reshaped
        self.labels = cd_Labels
        
    def __len__(self):
        return len(self.features_reshaped)

    def __getitem__(self, index):
        return (self.features_reshaped[index], self.labels[index])

In [109]:
class ActivityMonitoring_FC(nn.Module):

    def __init__(self):
        super(ActivityMonitoring_FC, self).__init__()
        
        self.fc11 = nn.Linear(804 , 1024)  #msacc # flatten inpu dimension
        
        
        self.fc21 = nn.Linear(1024 , 512)
        
        self.fc3 = nn.Linear(1024 , 512)
        self.fc4 = nn.Linear(512 , 64)

        self.output = nn.Linear(64 , 2)

        self.dropout1 = nn.Dropout(p=0.3)
        self.dropout2 = nn.Dropout(p=0.3)

    def forward(self, features_reshaped):

        print("train_features_reshaped input shape:", features_reshaped.shape)
        print(self.fc11)
        print(features_reshaped.shape)
        features_reshaped = self.fc11(features_reshaped) #z-vector
        features_reshaped = F.relu(features_reshaped)
        features_reshaped = self.fc21(features_reshaped)
        features_reshaped = F.relu(features_reshaped)

        act = F.relu(self.fc3(features_reshaped))
        print("act shape after fc3: ", act.shape)
        
        act = self.dropout1(act)
        act = F.relu(self.fc4(act))
        print("act shape after fc4: ", act.shape)
        act = self.dropout2(act)
        act_out = self.output(act)
        print("act_out shape after output layer: ", act_out.shape)

        return act_out



In [110]:
#defining loss_fn, optimizer, model
lr = 0.01
act_model = ActivityMonitoring_FC()
optimizer_act = optim.Adam(act_model.parameters(), lr=lr) #for state activities
loss_fn = nn.CrossEntropyLoss()
batch_size = 10

In [111]:
train_dataset = CogAgeDataset(train_features_reshaped, train_Labels)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = CogAgeDataset(test_features_reshaped, test_Labels)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    

tttt: (2284, 108)
tttt: (2288, 108)


In [112]:
#training = 0
samples_tr = 0
correct_tr = 0
act_model.train()
n_epochs = 5
for epoch in range(n_epochs): #training loop
    batch_losses = []

    act_sample_tr = 0
    act_sample_ts = 0
    
    for features_reshaped, labels_tr in train_loader:
            # print("Dimensions of each sensor modality:")
            print(f"msAcc_tr: {features_reshaped.shape}")
            # print(f"msGyro_tr: {msGyro_tr.shape}")
            print(f"labels_tr: {labels_tr.shape}")

            
            #labels_tr  = labels_tr.to(device)
            
            optimizer_act.zero_grad()

            labels_predicted = act_model(features_reshaped)
            #labels_predicted = labels_predicted.flatten()
            labels_tr = labels_tr.type(torch.LongTensor)

            _, predicted_tr = torch.max(labels_predicted,1)
            #print("predicted_tr.shape", predicted_tr.shape)   

            samples_tr += labels_tr.size(0)
            correct_tr += (predicted_tr == labels_tr).sum().item()
            loss = loss_fn(labels_predicted, labels_tr)
            loss = loss.unsqueeze(0)
            epoch_loss = loss.item()
            print("Epoch, Loss:" , epoch,", ", epoch_loss)
            batch_losses.append(loss.item())
            
            loss.backward()
            optimizer_act.step()

    act_loss = sum(batch_losses)/len(batch_losses)
        #average_loss[1].append(bbh_loss)
    accr = 100.0 * correct_tr / samples_tr

    print(f"epoch: {epoch}")
    print(f"Training: batch_loss: {act_loss:.3f}, Accuracy: {accr:.3f}")
    #print(f"Training: batch_loss: {act_loss:.3f}, {state_correct_tr}/{state_samples_tr}, state_acc: {state_acc:.3f}%,  bbh_loss: {bbh_loss:.3f}, {bbh_correct_tr}/{bbh_samples_tr} , bbh_acc: {bbh_acc:.3f}%")

 

msAcc_tr: torch.Size([10, 108])
labels_tr: torch.Size([10])
train_features_reshaped input shape: torch.Size([10, 108])
Linear(in_features=804, out_features=1024, bias=True)
torch.Size([10, 108])


RuntimeError: mat1 and mat2 must have the same dtype